apiVersion: v1
kind: Service
metadata:
  name: modern-blog-api
spec:
  type: NodePort
  ports:
   - port: 4000
     targetPort: 4000
     protocol: TCP
     nodePort: 30400
  selector:
    app: modern-blog-api