piVersion: apps/v1
kind: Deployment
metadata:
  name: modern-blog-api-deployment
spec:
  selector:
    matchLabels:
      app: modern-blog-api
  replicas: 1
  template:
    metadata:
      labels:
        app: modern-blog-api
    spec:
      containers:
        - name: modern-blog-api
          image: ./api
          ports:
            - containerPort: 3000
