version: "3"
services:
  front:
    image: node:16
    volumes:
      - ./:/usr/src
      - root_modules:/usr/src/node_modules
      - front_modules:/usr/src/front/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn && cd front && yarn && yarn dev"
    tty: true
    ports:
      - "3000:3000"
    environment:
      API_URL_SSR: "http://api:4000"
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
      CHOKIDAR_USEPOLLING: true
  api:
    image: node:16
    volumes:
      - ./:/usr/src
      - root_modules:/usr/src/node_modules
      - api_modules:/usr/src/api/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    ports:
      - "4000:4000"
    command: sh -c "yarn && cd api && yarn && yarn dev"
    depends_on:
      - db
    environment:
      CLIENT_ORIGIN_URL: "http://localhost:3000"
      DB_HOST: "db"
      DB_USERNAME: "root"
      DB_PASSWORD: "docker"
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql #データ永続化
      - ./db/sql:/docker-entrypoint-initdb.d #起動時sqlフォルダ内のsqlファイルを実行
  phpmyadmin:
    image: phpmyadmin #fpmやalpineタグは別途httpサーバが必要
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin:/sessions"
    depends_on:
      - db
volumes:
  front_modules:
  api_modules:
  root_modules: