apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-blog-front
spec:
  selector:
    matchLabels:
      app: modern-blog-front
  replicas: 1
  template:
    metadata:
      labels:
        app: modern-blog-front
    spec:
      containers:
        - name: modern-blog-front
          image: volgakurvar/modernblog-front:1.0
          ports:
            - containerPort: 3000
          env:
            - name: API_URL_SSR
              value: http://modern-blog-api:4000
            - name: NEXT_PUBLIC_API_URL
              value: http://localhost:30400