apiVersion: v1
kind: Service
metadata:
  name: modern-blog-front
spec:
  type: NodePort
  ports:
   - port: 3000
     targetPort: 3000
     protocol: TCP
     nodePort: 30300
  selector:
    app: modern-blog-front